# build file

import os

# Config
target_name = "proconlib-demo"
src = "main.cpp"

# Build Environment
env = Environment(ENV=os.environ.copy())
env.Append(CCFLAGS=["-std=c++2c"])

# Library
## SDL3
env.ParseConfig("pkg-config sdl3 --libs-only-L --libs-only-l --cflags")

## proconlib
env.Append(CPPPATH=[".."])

## GamepadMotionHelpers
env.Append(CPPPATH=[".."])
env.Append(CCFLAGS=["-Wno-comment"])

## raylib
env.ParseConfig("pkg-config raylib --libs-only-L --libs-only-l --cflags")

# Executable
program = env.Program(
    target=target_name,
    source=src,
)

# Default Build Target
Default(program)
